# Tensor Basics

In [1]:
import tensorflow as tf

### Initialization of Tensors

In [12]:
a = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(a)
b = tf.constant([[1,2,3],[4,5,6]])
print(b)
c = tf.ones((3,3))
print(c)
d = tf.zeros((2,3))
print(d)
e = tf.eye(3)
print(e)
f = tf.random.normal((3,3), mean=0, stddev=1)
print(f)
g = tf.random.uniform((1,3), minval=0, maxval=1)
print(g)
h = tf.range(9)
print(h)
i = tf.range(start=1, limit=10, delta=2)
print(i)
# tf.float(16, 32, 64)
# tf.int(8, 16, 32, 64)
# tf.bool
i = tf.cast(i, dtype=tf.float64)
print(i)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.5299997  -0.42962843  1.2221533 ]
 [ 0.7909484   2.1177316  -0.6126505 ]
 [-0.97200906 -0.9406563  -1.6109722 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.4138373 0.7402588 0.8783786]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


### Mathematical Operations

In [20]:
x = tf.constant([1,2,3])
y = tf.constant([2,3,4])
# 元素相加
z = tf.add(x,y)
z = x + y
print(z)
# 元素相减
z = tf.subtract(x,y)
z = x - y
print(z)
# 元素相除
z = tf.divide(x,y)
z = x / y
print(z)
# 元素相乘
z = tf.multiply(x,y)
z = x * y
print(z)
# 元素相乘求和
z = tf.tensordot(x,y,axes=1)
z = tf.reduce_sum(x*y, axis=0)
print(z)
# 元素幂
z = x ** 2
print(z)
# 矩阵乘法
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([-1 -1 -1], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.66666667 0.75      ], shape=(3,), dtype=float64)
tf.Tensor([ 2  6 12], shape=(3,), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)
tf.Tensor(
[[ 2.1087296  -2.4355235  -2.5608373  -3.275873  ]
 [-0.39130768  4.7316785   0.3768755  -0.2707536 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 2.1087296  -2.4355235  -2.5608373  -3.275873  ]
 [-0.39130768  4.7316785   0.3768755  -0.2707536 ]], shape=(2, 4), dtype=float32)


### Indexing

In [26]:
x = tf.constant([0,1,1,2,3,1,2,1,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)
y = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(y[0,:])
print(y[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 1 3], shape=(9,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 1 3], shape=(8,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2 3], shape=(5,), dtype=int32)
tf.Tensor([3 1 2 1 3 2 1 1 0], shape=(9,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Reshaping

In [30]:
x = tf.range(9)
print(x)
x = tf.reshape(x, (3,3))
print(x)
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
